In [1]:
import numpy as np

In [2]:
def relu(x):
  return np.maximum(0,x)

In [3]:
relu(10)

np.int64(10)

In [4]:
relu(-10)

np.int64(0)

In [6]:
relu(np.array([-1,0,1,2,-5,11]))

array([ 0,  0,  1,  2,  0, 11])

In [7]:
def leky_relu(x, alpha=0.01):
  return np.where(x>0, x, x*alpha)

In [8]:
leky_relu(-10)

array(-0.1)

In [9]:
leky_relu(np.array([-3,-2,0,2,4]))

array([-0.03, -0.02,  0.  ,  2.  ,  4.  ])

In [10]:
def elu(x, alpha=1.0):
  return np.where(x>0,x,alpha*(np.exp(x)-1))

In [11]:
elu(5)

array(5.)

In [12]:
elu(np.array([-3,-2,0,2,4]))

array([-0.95021293, -0.86466472,  0.        ,  2.        ,  4.        ])

In [13]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [14]:
sigmoid(np.array([-3,-2,0,2,4]))

array([0.04742587, 0.11920292, 0.5       , 0.88079708, 0.98201379])

In [16]:
def softmax(x):
  e_x=np.exp(x-np.max(x))
  return e_x/e_x.sum(axis=0)

In [18]:
y=softmax(np.array([-1,0,3]))

In [19]:
y

array([0.01714783, 0.04661262, 0.93623955])

In [20]:
sum(y)

np.float64(1.0)

In [21]:
def swish(x, beta=1.0):
  return x*sigmoid(beta*x)

In [22]:
swish(5)

np.float64(4.966535745378576)

In [26]:
swish(np.array([2,3,-1,0]))

array([ 1.76159416,  2.85772238, -0.26894142,  0.        ])

In [27]:
def linear(x):
  return x

In [28]:
linear(10)

10

In [29]:
linear(np.array([1,2,-1,3,4.6,0]))

array([ 1. ,  2. , -1. ,  3. ,  4.6,  0. ])

In [30]:
def tanh(x):
  return np.tanh(x)


In [31]:
tanh(10)

np.float64(0.9999999958776927)

In [32]:
tanh([1,2,3,0,-2])

array([ 0.76159416,  0.96402758,  0.99505475,  0.        , -0.96402758])

In [2]:
def sigmod(z):
  return 1/(1+np.exp(-z))

In [3]:
def feedforward(weight,bias,input):
  total=sum(w * x for w,x in zip(weight,input))+bias
  return sigmod(total)


In [4]:
def classify(output,threshold=0.5):
  return 1 if output>threshold else 0

In [5]:
weight=[0,1]
bias=4
input=[2,3]
output=feedforward(weight,bias,input)
print(f'output of the neorun for input {input} is {output}')

output of the neorun for input [2, 3] is 0.9990889488055994


In [6]:
class_level=classify(output)
print(f'class level is {class_level}')

class level is 1
